create table if not exists public.webinars (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  subtitle text,
  description text,
  format text not null default 'Free live online webinar',
  speaker_name text,
  speaker_title text,
  speaker_biography text,
  speaker_image_url text,
  event_start_at timestamptz,
  event_end_at timestamptz,
  registration_opens_at timestamptz,
  registration_closes_at timestamptz,
  timezone text not null default 'Europe/London',
  meeting_provider text,
  meeting_url text,
  maximum_attendees integer,
  status text not null default 'draft'
    check (status in ('draft','published','registration_closed','live','completed','cancelled')),
  recording_available boolean not null default false,
  recording_url text,
  masterclass_url text,
  confirmation_email_enabled boolean not null default true,
  two_day_reminder_enabled boolean not null default true,
  one_hour_reminder_enabled boolean not null default true,
  follow_up_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.webinar_registrations (
  id bigint generated by default as identity primary key,
  webinar_id bigint not null references public.webinars(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  full_name text not null,
  email text not null,
  email_normalised text not null,
  phone text,
  organisation text,
  role text not null,
  automation_goal text,
  event_consent boolean not null,
  event_consent_at timestamptz not null,
  marketing_consent boolean not null default false,
  marketing_consent_at timestamptz,
  registration_status text not null default 'registered'
    check (registration_status in ('registered','waitlisted','cancelled','attended','no_show')),
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  referrer_url text,
  landing_page text,
  user_agent text,
  ip_hash text,
  unsubscribe_token text not null unique,
  confirmation_token text not null unique,
  confirmation_sent boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (webinar_id, email_normalised)
);

create table if not exists public.webinar_email_queue (
  id bigint generated by default as identity primary key,
  webinar_id bigint not null references public.webinars(id) on delete cascade,
  registration_id bigint not null references public.webinar_registrations(id) on delete cascade,
  email_type text not null,
  scheduled_for timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending','processing','sent','delivered','failed','cancelled')),
  attempt_count integer not null default 0,
  provider text not null default 'brevo',
  provider_message_id text,
  last_error text,
  processing_started_at timestamptz,
  sent_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (registration_id, email_type)
);

create table if not exists public.webinar_email_events (
  id bigint generated by default as identity primary key,
  email_queue_id bigint references public.webinar_email_queue(id) on delete set null,
  registration_id bigint not null references public.webinar_registrations(id) on delete cascade,
  webinar_id bigint not null references public.webinars(id) on delete cascade,
  event_type text not null,
  provider_event_id text unique,
  event_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists webinar_registration_status_idx
  on public.webinar_registrations(webinar_id, registration_status);
create index if not exists webinar_email_due_idx
  on public.webinar_email_queue(status, scheduled_for);

insert into public.webinars (
  title, slug, subtitle, description, event_start_at, timezone, status, masterclass_url
) values (
  'Build Your First AI Employee That Works 24/7—Without Coding',
  'build-your-first-ai-employee',
  'Agentic AI for Everyone',
  'Learn how to design an AI employee that supports customers, organises information and automates repetitive work without traditional coding.',
  '2026-08-08T13:00:00Z',
  'Europe/London',
  'published',
  '/masterclass'
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  event_start_at = excluded.event_start_at,
  timezone = excluded.timezone,
  status = excluded.status,
  updated_at = now();
